name: AspNetCoreSettingsProtection build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install dependencies
      run: dotnet restore AspNetCoreSettingsProtection.csproj
      working-directory: src
    - name: Build
      run: dotnet build --configuration Release --no-restore
