name: AspNetCoreSettingsProtection publish to nuget

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install dependencies
      run: dotnet restore AspNetCoreSettingsProtection.csproj
      working-directory: src
    - name: Build
      run: dotnet build AspNetCoreSettingsProtection.csproj --configuration Release --no-restore
      working-directory: src
    - name: Package
      run: dotnet pack --no-build --configuration Release src/AspNetCoreSettingsProtection.csproj --output .
    - name: PushNuget
      run: dotnet nuget push bin/Release/AspNetCoreSettingsProtection*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate